name: Regenerate the Coveo index XML
on:
  push:
    branches:
      - 1099
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Regenerate coveo.xml
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        working-directory: ./coveo
        run: |
          node generate-coveo-sitemap.js
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./coveo-xml.xml
          git commit -m "Update generated coveo.xml file"
          git push
